### ISSUE TITLE
TypeError: Failed to construct 'PasswordCredential': 'id' must not be empty.

### ISSUE THREAD

**Issue by nhnb** [GoogleChrome/credential-management-sample#6]
Password login does not work in the demo application. As far as I can tell, the root cause is this code in `onRegister`

```
    if (navigator.credentials) {
      // Create password credential
      var cred = new PasswordCredential(regForm);     // <-------- Error is thrown here
      cred.idName = 'email';
      cred.name = profile.name;
      cred.iconURL = profile.imageUrl;

      // Store user information as this is registration using id/password
      navigator.credentials.store(cred);
    }
```

This code creates a PasswordCredential object based on the registration form. The idName variable is empty during the constructor call. Therefore it defaults to "username". The html code, however, does not have a "username" input field. Therefore the following error is thrown by the constructor:

```TypeError: Failed to construct 'PasswordCredential': 'id' must not be empty.```

The code tries to set `idName` to `email` later, but this statement is not execute because the exception occurs in the constructor.

**Comment by agektmr** [comment]
The issue should be caused by this: https://bugs.chromium.org/p/chromium/issues/detail?id=651298
Can you it again using Chrome beta channel?

**Comment by nhnb** [comment]
Yes, indeed, on Chrome beta, it picks up the autocomplete="username email" attribute, and everything works.

**Comment by agektmr** [comment]
Thanks for reporting this issue.
To be clear, this change (multi tokens in `autocomplete`) was only recently added. Sorry for your confusion. M56 will be stable next month.
